parameters:
#    vdm_extractor_api.example.class: VDMExtractor\APIBundle\Example

services:
#    vdm_extractor_api.example:
#        class: %vdm_extractor_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
